language: php
php:
  - '7.1'
cache:
  directories:
  - $HOME/.composer/cache/files
install:
  - composer install
  - ant
script:
  - phpunit
addons:
  code_climate:
    repo_token: f21bdaad7805806dccb242386068cd95cb5dc08149477d9b0f1aa266d3e5111b
after_success:
  - vendor/bin/test-reporter
